language: node_js
node_js: "stable"
branches:
  only:
    -master
install: npm install
cache:
  directories:
    -"node_modules"
services:
  -mongodb
before_script:
  -mongo task-manager-api-test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'