sudo: false
language: node_js
node_js:
  - "10.15.1"
install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run test
services:
  - mongodb

before_script:
  - mongo task-manager-api-test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});
