sudo: false
language: node_js
node_js:
  - "10.15.1"
install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run test
after_success:
  - npm run coveralls

services:
  - mongodb

before_script:
  -mongo task-manager-api-test
